############################
## Author
############################

author:
  name: 'Bayou Mountain Holdings, LLC'
  image: author.png
  greeting: ':computer:  A Diverse Holdings Company  :shaved_ice:'
  icon: ':mount_fuji:'

############################
## Links
############################

links:
  - github: https://github.com/BayouMountainHoldings
  # - gitlab:
  # - facebook: https://github.com/chrede88/qubt
  # - x-twitter:
  # - mastodon:
  # - linkedin: https://github.com/chrede88/qubt
  # - instagram: https://github.com/chrede88/L1nkr
  # - reddit:
  # - telegram:
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  - email: "mailto:info@bayoumountain.holdings"
  - website: https://techrelay.pro/
  - website: https://bayousno.co 
  # - link:
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow:
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  # - youtube:
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bluesky:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  # - paypal:
  # - pgp-key:
  # - windows:
  # - codeberg:
  # - pixelfed:
  # - substack:
  # - newsletter:

###############################
## OpenGraph & Twitter Cards
###############################

title: 'Bayou Mountain Holdings, LLC'
description: 'A Diverse Holdings Company'
images:
  - thumbnail.png

###############################
## Latex math
###############################

# To configure Latex rendering on all pages, change to: true
#
# To only add Latex rendering on pages that need it, set in the frontmatter
# of each page that needs it:
#   params:
#     math: true
# This option will allow better performance, as it'll only load
# the extra JS when needed.
math: false
